# Terminology {-}

This section will briefly introduce you to the terms that we will use 
throughout this book. 

- __Data table__: rectangular array formed by rows and columns. In each of
the table entries (i.e. intersection of one row and one column), we find a
datum, typically codified in numeric form. We also use the term _data amtrix_
as a synonym term. We represent the data table with upper case bold letters
e.g. $\mathbf{X}$, with $n$ rows and $p$ columns.

- __Individual__: an individual is a row of the data table. The word individual
refers to any type of object: person, animal, country, company, planet, etc.

- __Variable__: we use the word "variable" to refer to any column in the data table. For each individual, we observe the same aggragate, the same measure, the same question, etc. Instead of variable we can also talk about "measure", attribute, characteristic, property, etc.

- __Continuous Variable__: we talk about continuous variable when the measurement is quantitative. To be more precise, a varibale is continuous when calculating the mean (or average) makes sense.

- __Nominal Varibale__: we talk about a nominal variable when its values are names of categories (or qualities). Examples of nominal variables are _civil status_ (e.g. single, married, divorced, widowed), _geographc region_ (e.g. north, south, west, etc). We also use the terms categorical or qualitative variable as synonyms of nominal.

- __Modality__: the modalities or categories are the values taken by a nominal variable. For example the variable _gender_ (typical) has two modalities: male and female. A modalitiy is also known as group, class, or category.

- __Cloud of Points__: on a plane or in a three-dimensional space, the notion of "cloud of points" has to do with how the points are positioned according to a series of coordinates, which are based on a set of orthogonal axes. Given the coordinates of the points, it is easy to calculate distance between them. When we have more than three axes, even though the cloud of points exist, we cannot visualize them.

- __Distance__: the distance between two points in a given cloud coincides with the usual notion of distance (which can be calculated based on the coordinates of the points via the famous Pythogorean theorem).

- __Inertia__: inertia is a borrowed term from Mechanics (in Physics) which is entirely equivalent to the statistical concept of variance. The inertia gives an idea of the spread in a cloud of weighted points. If the individuals have the same weight (same importance), the direction with the larger inertia of the cloud is the direction of its major axis.

- __Center of Gravity__: this is the average point (or central point) in a cloud of weighted points. Therefore, there is an equivalence between the mechanical notion of center of gravity and the statistical notion of average point.

- __Factorial Analysis__: optimal visualization (in a certain sense) of a cloud of points in some multidimensional space.

- __Factorial Axes__: these are the axes, sorted by importance, which we use to visualize the cloud of points in a factorial analysis. They are defined by the directions of larger stretching (inertia) of the cloud of poitns.

- __PCA__: Principal Component(s) Analysis.

- __Active Variables__: set of variables that are used in the computation of the axes for the factorial planes.

- __Supplementary Variables__: set of variables that are NOT used in the computation of the factorial axes, but that can be used as aid in the interpretation of results.

- __Contribution__: measures the participation of an element (e.g. category, variable, frequency, or individual) in the construction of a factorial axis.

- __Squared Cosine__: measures the quality of the projection of an element (e.g. category, variable, frequency, or individual) along a factorial axis.

- __V-test__: measures, in number of standard deviations, the distance between an observed value and its theoretical value under a null hypothesis. This test is used to characterize the axes, the categories, the classes, etc.
